# Generated by Django 5.0.6 on 2024-05-08 06:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('en_form', models.CharField(max_length=50)),
                ('uz_form', models.CharField(max_length=200)),
                ('en_definition', ckeditor.fields.RichTextField()),
                ('uz_definition', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
